class AddTranslateRuToState <  SpreeExtension::Migration[4.2]
  def change
    Spree::State.find(3299).translation.update!(locale: "ru",name: "Винницкая")
    Spree::State.find(3300).translation.update!(locale: "ru",name: "Волынская")
    Spree::State.find(3301).translation.update!(locale: "ru",name: "Луганская")
    Spree::State.find(3302).translation.update!(locale: "ru",name: "Днепропетровская")
    Spree::State.find(3303).translation.update!(locale: "ru",name: "Донецкая")
    Spree::State.find(3304).translation.update!(locale: "ru",name: "Житомирская")
    Spree::State.find(3305).translation.update!(locale: "ru",name: "Закарпатская")
    Spree::State.find(3306).translation.update!(locale: "ru",name: "Запорожская")
    Spree::State.find(3307).translation.update!(locale: "ru",name: "Ивано-Франковская")
    Spree::State.find(3308).translation.update!(locale: "ru",name: "г.Киев")
    Spree::State.find(3309).translation.update!(locale: "ru",name: "Киевская")
    Spree::State.find(3310).translation.update!(locale: "ru",name: "Кировоградская")
    Spree::State.find(3311).translation.update!(locale: "ru",name: "г.Севастополь")
    Spree::State.find(3312).translation.update!(locale: "ru",name: "АР Крым")
    Spree::State.find(3313).translation.update!(locale: "ru",name: "Львовская")
    Spree::State.find(3314).translation.update!(locale: "ru",name: "Николаевская")
    Spree::State.find(3315).translation.update!(locale: "ru",name: "Одесская")
    Spree::State.find(3316).translation.update!(locale: "ru", name: "Полтавская")
    Spree::State.find(3317).translation.update!(locale: "ru",name: "Ровенская")
    Spree::State.find(3318).translation.update!(locale: "ru", name: "Сумская")
    Spree::State.find(3319).translation.update!(locale: "ru",name: "Тернопольская")
    Spree::State.find(3320).translation.update!(locale: "ru",name: "Харьковская")
    Spree::State.find(3321).translation.update!(locale: "ru",name: "Херсонская")
    Spree::State.find(3322).translation.update!(locale: "ru",name: "Хмельницкая")
    Spree::State.find(3323).translation.update!(locale: "ru",name: "Черкасская")
    Spree::State.find(3324).translation.update!(locale: "ru",name: "Черниговская")
    Spree::State.find(3325).translation.update!(locale: "ru",name: "Черновицкая")
  end
end
