class ChangeStateName <  SpreeExtension::Migration[4.2]
  def change
    Spree::State.find(3299).update!(name: "Вінницька")
    Spree::State.find(3300).update!(name: "Волинська")
    Spree::State.find(3301).update!(name: "Луганська")
    Spree::State.find(3302).update!(name: "Дніпропетровська")
    Spree::State.find(3303).update!(name: "Донецька")
    Spree::State.find(3304).update!(name: "Житомирська")
    Spree::State.find(3305).update!(name: "Закарпатська")
    Spree::State.find(3306).update!(name: "Запорізька")
    Spree::State.find(3307).update!(name: "Івано-Франківська")
    Spree::State.find(3308).update!(name: "м.Київ")
    Spree::State.find(3309).update!(name: "Київська")
    Spree::State.find(3310).update!(name: "Кіровоградська")
    Spree::State.find(3311).update!(name: "м.Севастополь")
    Spree::State.find(3312).update!(name: "Автономна Республіка Крим")
    Spree::State.find(3313).update!(name: "Львівська")
    Spree::State.find(3314).update!(name: "Миколаївська")
    Spree::State.find(3315).update!(name: "Одеська")
    Spree::State.find(3316).update!(name: "Полтавська")
    Spree::State.find(3317).update!(name: "Рівненська")
    Spree::State.find(3318).update!(name: "Сумська")
    Spree::State.find(3319).update!(name: "Тернопільська")
    Spree::State.find(3320).update!(name: "Харківська")
    Spree::State.find(3321).update!(name: "Херсонська")
    Spree::State.find(3322).update!(name: "Хмельницька")
    Spree::State.find(3323).update!(name: "Черкаська")
    Spree::State.find(3324).update!(name: "Чернігівська")
    Spree::State.find(3325).update!(name: "Чернівецька")
    Spree::Country.find(230).update!(name: "Україна")
  end
end
