class UkTranslateState < SpreeExtension::Migration[4.2]
  def change
    Spree::State.find(2774).update!(locale: "uk",name: "Вінницька")
    Spree::State.find(2775).update!(locale: "uk",name: "Волинська")
    Spree::State.find(2776).update!(locale: "uk",name: "Луганська")
    Spree::State.find(2777).update!(locale: "uk",name: "Дніпропетровська")
    Spree::State.find(2778).update!(locale: "uk",name: "Донецька")
    Spree::State.find(2779).update!(locale: "uk",name: "Житомирська")
    Spree::State.find(2780).update!(locale: "uk",name: "Закарпатська")
    Spree::State.find(2781).update!(locale: "uk",name: "Запорізька")
    Spree::State.find(2782).update!(locale: "uk",name: "Івано-Франківська")
    Spree::State.find(2783).update!(locale: "uk",name: "м.Київ")
    Spree::State.find(2784).update!(locale: "uk",name: "Київська")
    Spree::State.find(2785).update!(locale: "uk",name: "Кіровоградська")
    Spree::State.find(2786).update!(locale: "uk",name: "м.Севастополь")
    Spree::State.find(2787).update!(locale: "uk",name: "Автономна Республіка Крим")
    Spree::State.find(2788).update!(locale: "uk",name: "Львівська")
    Spree::State.find(2789).update!(locale: "uk",name: "Миколаївська")
    Spree::State.find(2790).update!(locale: "uk",name: "Одеська")
    Spree::State.find(2791).update!(locale: "uk",name: "Полтавська")
    Spree::State.find(2792).update!(locale: "uk",name: "Рівненська")
    Spree::State.find(2793).update!(locale: "uk",name: "Сумська")
    Spree::State.find(2794).update!(locale: "uk",name: "Тернопільська")
    Spree::State.find(2795).update!(locale: "uk",name: "Харківська")
    Spree::State.find(2796).update!(locale: "uk",name: "Херсонська")
    Spree::State.find(2797).update!(locale: "uk",name: "Хмельницька")
    Spree::State.find(2798).update!(locale: "uk",name: "Черкаська")
    Spree::State.find(2799).update!(locale: "uk",name: "Чернігівська")
    Spree::State.find(2800).update!(locale: "uk",name: "Чернівецька")
  end
end
