class AddTranslateRuToState <  SpreeExtension::Migration[4.2]
  def change
    Spree::State.find(2774).translation.update!(locale: "ru",name: "Винницкая")
    Spree::State.find(2775).translation.update!(locale: "ru",name: "Волынская")
    Spree::State.find(2776).translation.update!(locale: "ru",name: "Луганская")
    Spree::State.find(2777).translation.update!(locale: "ru",name: "Днепропетровская")
    Spree::State.find(2778).translation.update!(locale: "ru",name: "Донецкая")
    Spree::State.find(2779).translation.update!(locale: "ru",name: "Житомирская")
    Spree::State.find(2780).translation.update!(locale: "ru",name: "Закарпатская")
    Spree::State.find(2781).translation.update!(locale: "ru",name: "Запорожская")
    Spree::State.find(2782).translation.update!(locale: "ru",name: "Ивано-Франковская")
    Spree::State.find(2783).translation.update!(locale: "ru",name: "г.Киев")
    Spree::State.find(2784).translation.update!(locale: "ru",name: "Киевская")
    Spree::State.find(2785).translation.update!(locale: "ru",name: "Кировоградская")
    Spree::State.find(2786).translation.update!(locale: "ru",name: "г.Севастополь")
    Spree::State.find(2787).translation.update!(locale: "ru",name: "АР Крым")
    Spree::State.find(2788).translation.update!(locale: "ru",name: "Львовская")
    Spree::State.find(2789).translation.update!(locale: "ru",name: "Николаевская")
    Spree::State.find(2790).translation.update!(locale: "ru",name: "Одесская")
    Spree::State.find(2791).translation.update!(locale: "ru", name: "Полтавская")
    Spree::State.find(2792).translation.update!(locale: "ru",name: "Ровенская")
    Spree::State.find(2793).translation.update!(locale: "ru", name: "Сумская")
    Spree::State.find(2794).translation.update!(locale: "ru",name: "Тернопольская")
    Spree::State.find(2795).translation.update!(locale: "ru",name: "Харьковская")
    Spree::State.find(2796).translation.update!(locale: "ru",name: "Херсонская")
    Spree::State.find(2797).translation.update!(locale: "ru",name: "Хмельницкая")
    Spree::State.find(2798).translation.update!(locale: "ru",name: "Черкасская")
    Spree::State.find(2799).translation.update!(locale: "ru",name: "Черниговская")
    Spree::State.find(2800).translation.update!(locale: "ru",name: "Черновицкая")
  end
end
